[tool.poetry]
name = "sybricks"
version = "0.1.0"
description = ""
authors = ["Oujin <jean.zknowledge@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
